

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Cetak Data Riwayat hidup</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.5 -->
	
	<style>
		* {font-family: sans-serif; font-size: 13px;}
	    @page { margin: 50px 50px; }
	    #header { position: fixed; left: 0px; top: -180px; right: 0px; height: 150px; background-color: #fff; text-align: center; }
	    #footer { position: fixed; left: 710px; bottom: -160px; right: 0px; height: 150px; background-color: #fff; }
	    #comment{ position: fixed; left: -10px; bottom: -160px; right: 0px; height: 150px; background-color: #fff; font-size: 8;}
	    #footer .page:after { content: counter(page, upper-roman); }
	    .l1{margin-top: 0;}
	    .l2{margin-top: 20; margin-bottom: 20;}

	    table {width: 100%; margin-top: 0; margin-bottom: 5; margin-left: 130;table-layout: relative; }
		th, td {text-align: left; padding: 0px; }
		tr:nth-child(even){background-color: #f2f2f2}
		th { background-color: #fff; color: black;}
  	</style>
</head>

<body>
<?php
$id=$_GET['id'];



?>
	<h2 align="center" class="l1">Pensiun Tahun <?php echo date(Y) ?></h2>
	<hr class="l2">`
	<h3 align="center"></h3>

		  <table border="1" align="center" class="table table-bordered table-striped">
    <thead>
      <tr>

        <th width="15" align="center"><strong><center>No</center></strong></th>
        <th width="100" align="center"><strong><center>Nip</center></strong></th>
        <th width="120" align="center"><strong><center>Nama</center></strong></th>
        <th width="100" align="center"><strong><center>Jabatan</center></strong></th>
        <th width="100" align="center"><strong><center>Status</center></strong></th>
        <th width="70" align="center"><strong><center>Umur</center></strong></th>        
      </tr>
    </thead>

      <?php
      $getpensiun=mysql_fetch_array(mysql_query("select usia from usia_pensiun"));
      $getpensiun2=$getpensiun[0]-1;

      $q=mysql_query("select * from view_datapegawai_update where umur >='$getpensiun2' ");
      while($data=mysql_fetch_array($q)){
      $no++;

      $getjabatan=$data['jabatan'];
      $getjabatan2=mysql_fetch_array(mysql_query("select jenis_jabatan from jenis_jabatan where id='$getjabatan' "));

      $status=$data['status_peg'];
      $status2=mysql_fetch_array(mysql_query("select status_pegawai from master_statuspegawai where id='$status' "));

      ?>
      <tr>
        <td align="center"><?php echo $no ?></td>
        <td align="center"><?php echo $data['nip'] ?></td>
        <td align="center"><?php echo $data['gelar_depan'];echo'  ';echo $data['nama'];echo'  ';echo $data['gelar_belakang'] ?></td>
        <td align="center"><?php echo $getjabatan2[0] ?></td>
        <td align="center"><?php echo $status2[0] ?></td>
        <td align="center"><?php echo $data['umur'] ?> Tahun</td>
      </tr> 

    <?php
    }
    ?>  
  </table> 
		
<!-- 	<div id="comment"><p>Printed on <?php date_default_timezone_set('Asia/Jakarta'); echo date("d M Y : h i s") ?> | Generated by SIMPEG @RodjoLand.com at <?php ?></p>
	<div id="footer">
    	<p class="page"></p>
  	</div> -->

</body>

</html>