

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Cetak Data Riwayat hidup</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.5 -->
	
	<style>
		* {font-family: sans-serif; font-size: 13px;}
	    @page { margin: 50px 50px; }
	    #header { position: fixed; left: 0px; top: -180px; right: 0px; height: 150px; background-color: #fff; text-align: center; }
	    #footer { position: fixed; left: 710px; bottom: -160px; right: 0px; height: 150px; background-color: #fff; }
	    #comment{ position: fixed; left: -10px; bottom: -160px; right: 0px; height: 150px; background-color: #fff; font-size: 8;}
	    #footer .page:after { content: counter(page, upper-roman); }
	    .l1{margin-top: 0;}
	    .l2{margin-top: 20; margin-bottom: 20;}

	    table {width: 100%; margin-top: 0; margin-bottom: 5; margin-left: 130;table-layout: relative; }
		th, td {text-align: left; padding: 0px; }
		tr:nth-child(even){background-color: #f2f2f2}
		th { background-color: #fff; color: black;}
  	</style>
</head>

<body>
<?php
$id=$_GET['id'];

$tahun=$_POST['tahun'];

$id_peg=$_POST['id_peg'];
$id_peg2=mysql_fetch_array(mysql_query("select nip, nama, gelar_depan, gelar_belakang from data_pegawai where id='$id_peg'"));

?>
	<h2 align="center" class="l1">LAPORAN TEGURAN</h2>
	<hr class="l2">
	<h3 align="center"></h3>

	<h4>Tahun <?php echo $tahun ?></h4>
	</h4></h4>

	<table border="1" align="center">
		<thead>
			<tr>

				<th width="15" align="center" ><strong>No</strong></th>
				<th width="15" align="center" ><strong>Nama</strong></th>
				<th width="30" align="center" ><strong>No Surat</strong></th>
				<th width="50" align="center" ><strong>Tanggal Surat</strong></th>
				<th width="50" align="center" ><strong>Jenis Teguran</strong></th>
				<th width="50" align="center" ><strong>Alasan Teguran</strong></th>
				
			</tr>
		</thead>
			<?php
			$q=mysql_query("select * from rwt_teguran where tanggal like '%$tahun%' ");
			while($data=mysql_fetch_array($q)){
			$no++;

			$teguran=$data['nama_teguran'];
			$teguran2=mysql_fetch_array(mysql_query("select teguran from master_teguran where id='$teguran' "));

			$pegawai=$data['id_peg'];
			$pegawai2=mysql_fetch_array(mysql_query("select nip, nama, gelar_depan, gelar_belakang from data_pegawai where id='$pegawai'"));

			?>
			<tr>
				<td align="center"><?php echo $no ?></td>
				<td align="center" width="50"><?php echo $pegawai2['nama'] ?></td>
				<td align="center"><?php echo $data['no_surat'] ?></td>
				<td align="center"><?php echo date("d M Y", strtotime($data['tanggal'])) ?></td>
				<td align="center"><?php echo $teguran2[0] ?></td>
				<td align="center"><?php echo $data['alasan'] ?></td>
			</tr>	

		<?php
		}
		?>	
	</table>	
		
<!-- 	<div id="comment"><p>Printed on <?php date_default_timezone_set('Asia/Jakarta'); echo date("d M Y : h i s") ?> | Generated by SIMPEG @RodjoLand.com at <?php ?></p>
	<div id="footer">
    	<p class="page"></p>
  	</div> -->

</body>

</html>